# Generated by Django 4.1 on 2022-08-31 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.toy')),
            ],
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
    ]
