# Generated by Django 4.1 on 2022-08-31 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ability_delete_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(choices=[('W', 'Weapon'), ('I', 'Interchangeable body piece'), ('B', 'Bonus piece to build a special character')], default='W', max_length=10)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.toy')),
            ],
        ),
    ]
