# Generated by Django 4.1 on 2022-08-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_piece_options_piece_date_alter_piece_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='toy',
        ),
        migrations.AddField(
            model_name='toy',
            name='abilities',
            field=models.ManyToManyField(to='main_app.ability'),
        ),
    ]
