# Generated by Django 4.1 on 2022-09-01 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_ability_options_ability_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='abilities',
        ),
        migrations.AddField(
            model_name='ability',
            name='toy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.toy'),
        ),
    ]
